# dictionary used to initialize states and search terms associated with them
states = {  "AL" : { "name" : "Alabama", "abbr" : "AL" },
            "AK" : { "name" : "Alaska" , "abbr" : "AK" },
            "AZ" : { "name" : "Arizona" , "abbr" : "AZ" },
            "AR" : { "name" : "Arkansas" , "abbr" : "AR" },
            "CA" : { "name" : "California" , "abbr" : "CA" },
            "CO" : { "name" : "Colorado" , "abbr" : "CO" },
            "CT" : { "name" : "Connecticut" , "abbr" : "CT" },
            "DE" : { "name" : "Delaware", "abbr" : "DE" },
            "DC" : { "name" : "Washington, D.C.", "abbr" : "DC" },
            "FL" : { "name" : "Florida" , "abbr" : "FL" },
            "GA" : { "name" : "Georgia", "abbr" : "GA" },
            "HI" : { "name" : "Hawaii" , "abbr" : "HI" },
            "ID" : { "name" : "Idaho" , "abbr" : "ID" },
            "IL" : { "name" : "Illinois" , "abbr" : "IL" },
            "IN" : { "name" : "Indiana" , "abbr" : "IN" },
            "IA" : { "name" : "Iowa" , "abbr" : "IA" },
            "KS" : { "name" : "Kansas" , "abbr" : "KS" },
            "KY" : { "name" : "Kentucky" , "abbr" : "KY" },
            "LA" : { "name" : "Louisiana" , "abbr" : "LA" },
            "ME" : { "name" : "Maine" , "abbr" : "ME" },
            "MD" : { "name" : "Maryland" , "abbr" : "MD" },
            "MA" : { "name" : "Massachusetts" , "abbr" : "MA" },
            "MI" : { "name" : "Michigan" , "abbr" : "MI" },
            "MN" : { "name" : "Minnesota" , "abbr" : "MN" },
            "MS" : { "name" : "Mississippi" , "abbr" : "MS" },
            "MO" : { "name" : "Missouri" , "abbr" : "MO" },
            "MT" : { "name" : "Montana" , "abbr" : "MT" },
            "NE" : { "name" : "Nebraska" , "abbr" : "NE" },
            "NV" : { "name" : "Nevada" , "abbr" : "NV" },
            "NH" : { "name" : "New Hampshire" , "abbr" : "NH" },
            "NJ" : { "name" : "New Jersey" , "abbr" : "NJ" },
            "NM" : { "name" : "New Mexico" , "abbr" : "NM" },
            "NY" : { "name" : "New York" , "abbr" : "NY" },
            "NC" : { "name" : "North Carolina" , "abbr" : "NC" },
            "ND" : { "name" : "North Dakota" , "abbr" : "ND" },
            "OH" : { "name" : "Ohio" , "abbr" : "OH" },
            "OK" : { "name" : "Oklahoma" , "abbr" : "OK" },
            "OR" : { "name" : "Oregon" , "abbr" : "OR" },
            "PA" : { "name" : "Pennsylvania" , "abbr" : "PA" },
            "RI" : { "name" : "Rhode Island" , "abbr" : "RI" },
            "SC" : { "name" : "South Carolina" , "abbr" : "SC" },
            "SD" : { "name" : "South Dakota" , "abbr" : "SD" },
            "TN" : { "name" : "Tennessee" , "abbr" : "TN" },
            "TX" : { "name" : "Texas" , "abbr" : "TX" },
            "UT" : { "name" : "Utah" , "abbr" : "UT" },
            "VT" : { "name" : "Vermont" , "abbr" : "VT" },
            "VA" : { "name" : "Virginia" , "abbr" : "VA" },
            "WA" : { "name" : "Washington" , "abbr" : "WA" },
            "WV" : { "name" : "West Virginia" , "abbr" : "WV" },
            "WI" : { "name" : "Wisconsin" , "abbr" : "WI" },
            "WY" : { "name" : "Wyoming" , "abbr" : "WY" }

    }

# dictionary used to initialize candidates
candidates = {
	"1" : { "first" : "Hillary" , "last" : "Clinton" , "party" : "d" },
	"2" : { "first" : "Bernie" , "last" : "Sanders" , "party" : "d" },
	"3" : { "first" : "Donald" , "last" : "Trump" , "party" : "r" },
	"4" : { "first" : "Ted" , "last" : "Cruz" , "party" : "r" },
	"5" : { "first" : "John" , "last" : "Kasich" , "party" : "r" }
}
