# dictionary used to initialize states and search terms associated with them
states = {  "AL" : { "name" : "alabama", "abbr" : "AL", "search_terms" : ["alabama", "al"] },
            "AK" : { "name" : "alaska" , "abbr" : "AK", "search_terms" : ["alaska", "ak"] },
            "AZ" : { "name" : "arizona" , "abbr" : "AZ", "search_terms" : ["arizona", "az"] },
            "AR" : { "name" : "arkansas" , "abbr" : "AR", "search_terms" : ["arkansas", "ar"] },
            "CA" : { "name" : "california" , "abbr" : "CA", "search_terms" : ["california", "ca"] },
            "CO" : { "name" : "colorado" , "abbr" : "CO", "search_terms" : ["colorado", "co"] },
            "CT" : { "name" : "connecticut" , "abbr" : "CT", "search_terms" : ["connecticut", "ct"] },
            "DE" : { "name" : "delaware", "abbr" : "DE" , "search_terms" : ["delaware", "de"] },
            "FL" : { "name" : "florida" , "abbr" : "FL", "search_terms" : ["florida", "fl"] },
            "GA" : { "name" : "georgia", "abbr" : "GA", "search_terms" : ["georgia", "ga"] },
            "HI" : { "name" : "hawaii" , "abbr" : "HI", "search_terms" : ["hawaii", "hi"] },
            "ID" : { "name" : "idaho" , "abbr" : "ID", "search_terms" : ["idaho", "id"] },
            "IL" : { "name" : "illinois" , "abbr" : "IL", "search_terms" : ["illinois", "il"] },
            "IN" : { "name" : "indiana" , "abbr" : "IN", "search_terms" : ["indiana", "in"] },
            "IA" : { "name" : "iowa" , "abbr" : "IA" , "search_terms" : ["iowa", "ia"] },
            "KS" : { "name" : "kansas" , "abbr" : "KS", "search_terms" : ["kansas", "ks"] },
            "KY" : { "name" : "kentucky" , "abbr" : "KY", "search_terms" : ["kentucky", "ky"] },
            "LA" : { "name" : "louisiana" , "abbr" : "LA", "search_terms" : ["louisiana", "la"] },
            "ME" : { "name" : "maine" , "abbr" : "ME", "search_terms" : ["maine"] },
            "MD" : { "name" : "maryland" , "abbr" : "MD", "search_terms" : ["maryland", "md"] },
            "MA" : { "name" : "massachusetts" , "abbr" : "MA", "search_terms" : ["massachusetts", "ma"] },
            "MI" : { "name" : "michigan" , "abbr" : "MI", "search_terms" : ["michigan", "mi"] },
            "MN" : { "name" : "minnesota" , "abbr" : "MN", "search_terms" : ["minnesota", "mn"] },
            "MS" : { "name" : "mississippi" , "abbr" : "MS", "search_terms" : ["mississippi", "ms"] },
            "MO" : { "name" : "missouri" , "abbr" : "MO", "search_terms" : ["missouri", "mo "] },
            "MT" : { "name" : "montana" , "abbr" : "MT", "search_terms" : ["montana", "mt"] },
            "NE" : { "name" : "nebraska" , "abbr" : "NE", "search_terms" : ["nebraska", "ne"] },
            "NV" : { "name" : "nevada" , "abbr" : "NV", "search_terms" : ["nevada", "nv"] },
            "NH" : { "name" : "new hampshire" , "abbr" : "NH", "search_terms" : ["new hampshire", "nh"] },
            "NJ" : { "name" : "new jersey" , "abbr" : "NJ", "search_terms" : ["new jersey", "nj"] },
            "NM" : { "name" : "new mexico" , "abbr" : "NM", "search_terms" : ["new mexico", "nm"] },
            "NY" : { "name" : "new york" , "abbr" : "NY", "search_terms" : ["new york", "ny"] },
            "NC" : { "name" : "north carolina" , "abbr" : "NC", "search_terms" : ["north carolina", "nc"] },
            "ND" : { "name" : "north dakota" , "abbr" : "ND", "search_terms" : ["north dakota", "nd"] },
            "OH" : { "name" : "ohio" , "abbr" : "OH", "search_terms" : ["ohio", "oh"] },
            "OK" : { "name" : "oklahoma" , "abbr" : "OK", "search_terms" : ["oklahoma", "ok"] },
            "OR" : { "name" : "oregon" , "abbr" : "OR", "search_terms" : ["oregon", "or"] },
            "PA" : { "name" : "pennsylvania" , "abbr" : "PA", "search_terms" : ["pennsylvania", "pa"] },
            "RI" : { "name" : "rhode island" , "abbr" : "RI", "search_terms" : ["rhode island", "ri"] },
            "SC" : { "name" : "south carolina" , "abbr" : "SC", "search_terms" : ["south carolina", "sc"] },
            "SD" : { "name" : "south dakota" , "abbr" : "SD", "search_terms" : ["south dakota", "sd"] },
            "TN" : { "name" : "tennessee" , "abbr" : "TN", "search_terms" : ["tennessee", "tn"] },
            "TX" : { "name" : "texas" , "abbr" : "TX", "search_terms" : ["texas", "tx"] },
            "UT" : { "name" : "utah" , "abbr" : "UT", "search_terms" : ["utah", "ut"] },
            "VT" : { "name" : "vermont" , "abbr" : "VT", "search_terms" : ["vermont", "vt"] },
            "VA" : { "name" : "virginia" , "abbr" : "VA", "search_terms" : ["virginia", "va"] },
            "WA" : { "name" : "washington" , "abbr" : "WA", "search_terms" : ["washington", "wa"] },
            "WV" : { "name" : "west virginia" , "abbr" : "WV", "search_terms" : ["west virginia", "wv"] },
            "WI" : { "name" : "wisconsin" , "abbr" : "WI", "search_terms" : ["wisconsin", "wi"] },
            "WY" : { "name" : "wyoming" , "abbr" : "WY", "search_terms" : ["wyoming", "wy"] }

    }

# dictionary used to initialize candidates
candidates = {
	"1" : { "first" : "Hillary" , "last" : "Clinton" , "party" : "d" },
	"2" : { "first" : "Bernie" , "last" : "Sanders" , "party" : "d" },
	"3" : { "first" : "Donald" , "last" : "Trump" , "party" : "r" },
	"4" : { "first" : "Ted" , "last" : "Cruz" , "party" : "r" },
	"5" : { "first" : "John" , "last" : "Kasich" , "party" : "r" }
}
