# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(default='', max_length=2, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=50)),
                ('sentiment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Candidate')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.State')),
            ],
        ),
        migrations.AddField(
            model_name='searchterm',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.State'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=models.ManyToManyField(to='engine.State'),
        ),
    ]
