# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(default='', max_length=2),
        ),
    ]
