# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20160405_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='state',
            new_name='states',
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('d', 'democratic'), ('r', 'republican'), ('o', 'other')], default='o', max_length=1),
        ),
    ]
