# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 03:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20160416_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
