# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20160418_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('state',)},
        ),
    ]
