# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20160426_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
