# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20160426_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('candidate', 'state')},
        ),
    ]
