# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20160426_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('state', 'candidate')},
        ),
    ]
